### ISSUE TITLE
قرار دادن مثال زبان سی‌شارپ با httpclient

### ISSUE THREAD

**Issue by ehsanasgarian** [Text-Mining/docs#1]
به نظر من، مثال زبان سی‌شارپ در مستندات را با 
HttpClient
مشابه مستندات فایل CHM
باشه خیلی بهتره هم کوتاه تر و راحتتر هست و هم نیازی به افزودن کتابخانه اضافه به پروژه نیست

**Comment by Hameds** [comment]
انجام شد
